### ISSUE TITLE
Resize stripboard is adding strips the wrong way

### ISSUE THREAD

**Issue by aknoerig** [fritzing/fritzing-app#2998]
_From [Martin.B...@gmail.com](https://code.google.com/u/100779990985978385285/) on September 10, 2014 16:45:22_

What steps will reproduce the problem? 1. Drag a stripboard to Breadboard view
2. Resize it to e.g. 30 x 30 (becomes very slow)
3. Original stripboard looks fine, the added holes are not stripboard Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? Expected output is a larger stripboard. Looks like added holes are added the wrong way What version of Fritzing are you using? On what operating system? Version 0.9.0 (bda4e 2014-06-11) 64 [Qt 4.8.5] on Linux (PCLinuxOS 64 bit) Please provide any additional information below.

**Attachment:** [Reed.fzz](http://code.google.com/p/fritzing/issues/detail?id=2998)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2998_

**Comment by GregWoods** [comment]
Is Fritzing dead? This bug is still present, 3 years later

**Comment by SilverNodashi** [comment]
Yes it's dead

**Comment by failiz** [comment]
@SilverNodashi  @GregWoods  dead revive sometimes :-)
remove imported label, add stripboard label

**Comment by hxlnt** [comment]
+1, please fix. (Are repo owners hiding user comments on this bug? If so--why?)

**Comment by failiz** [comment]
@hxlnt , the comments were out of topic, but owners are not hiding anything, you can press the button "Show comment" to see them.
In any case, I just pushed a fix for the issue. Lets hope that it is accepted and does not create new errors. Until is merged and there is a new release, you can see #3090 for a handy workaround.

**Comment by georgyfarniev** [comment]
The issue is still here, in 2021. Feels like fritzing is abandoned.

**Comment by failiz** [comment]
@georgyfarniev , Fritzing development was frozen for a few years and restarted two years ago. 

This bug has been fixed, and it will be released in 0.9.9. If you are able to compile Fritzing, you can test the fix in my pull request. If not, check  #3090 for a handy workaround.
