### ISSUE TITLE
Gerber files contain weird sections

### ISSUE THREAD

**Issue by markthepiggy** [fritzing/fritzing-app#3185]
There is s problem with the way Fritzing generates gerber files for some components. 

Rather than smooth lines, the pads of some components are constructed with lots of little steps. The issue can be seen in the following screen shots taken from Online Gerber viewer (http://www.gerber-viewer.com/default.aspx).

This is the board showing the field of view:

![image](https://cloud.githubusercontent.com/assets/8985791/12813900/2eaf28d0-cb8f-11e5-91c3-2b2819ff4a81.png)

and here is the enlarged section of interest:

![image](https://cloud.githubusercontent.com/assets/8985791/12813860/e54190d4-cb8e-11e5-9b42-1b823cb2ba16.png)

You can see that the pad on the bottom is made up of a smooth arc. This cuts very quickly on a cnc mill. The track is also ok. The top pad is made up of lots of jagged lines. This cuts very slowly.

The bottom pad is from the component 'RJ45 Jack'. The top pad is from the component 'Generic Female Header'. 

I also exported the board as an svg. The svg shows no sign of the problem:

![image](https://cloud.githubusercontent.com/assets/8985791/12814161/0e59813c-cb91-11e5-99c4-ba3da24562ce.png)

I have not been able to find any reports of this problem using Google or in the Fritzing bug tracker.

I am using Version 0.9.2 on windows 10.

**Comment by markthepiggy** [comment]
This issue looks like it has been addressed by an outstanding pull request byt nraynaud on May 13, 2015. There are obviously some issues with the pull request, but it would be great to get these fixed and incorporate the changes.

**Comment by KjellMorgenstern** [comment]
Unfortunately the gerber export pull request had to be reverted, so this issue probably still exists.
