### ISSUE TITLE
In schematic right clicking then moving a label causes a jump in position

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3895]
## Current Behaviour

If you place a part in schematic, then right click on the label and move it slightly (1 grid line in this case) the position jumps a large distance.

![capture](https://user-images.githubusercontent.com/16514277/138478106-22b38dc5-09e4-45d4-9ee0-5c16a951c4de.jpg)

like this

![capture1](https://user-images.githubusercontent.com/16514277/138478393-9bc40b65-4616-475d-8c40-794443ab6923.jpg)

if you left click on the label and move it it moves as expected only 1 grid line without jumping a large (and apparently random) direction,.

**Build:**

Version 0.9.9 
(bCD-348-0-f0af53a9 2021-09-22) 64 [Qt 5.15.2]

**Operating System:**
Windows 10

**Steps to reproduce:**
- See current behaviour

## Expected Behaviour
The label should move with the mouse as a left mouse click does not jump.

**Comment by KjellMorgenstern** [comment]
Right click will show the context of the label:
![image](https://user-images.githubusercontent.com/6494025/141635466-52714478-6926-4d93-9631-1f67f20c64b4.png)

**Comment by KjellMorgenstern** [comment]
I have trouble to reproduce this issue. But when I right-click on a label, it can not be moved at all in Fritzing 0.9.9 ? We have fixed a similar issue related to undo/redo, but I think that was already in 0.9.7

**Comment by failiz** [comment]
I could reproduce it in 0.9.9. I think you have to move the label first (with the left button) and then try to right click.

**Comment by failiz** [comment]
Still an issue in 1.0.2.

Steps:
* Add a resistor
* Move the label.
* Right-click on the label and hold the right-click! Then move the mouse while holding the right-click.
Then the label jumps. Easily reproducible.
(The right-click menu only appears when releasing the right-click.)

**Comment by KjellMorgenstern** [comment]
Trying to reproduce this here, but the right click menu immediately appears when pressing the right mouse button.

When you right click the resistor itself, does the menu also delay until the button is released again?

**Comment by KjellMorgenstern** [comment]
Which input device are you using? Mouse or touchpad? I am currently testing on Linux, with a mouse.

**Comment by failiz** [comment]
I'm in windows with a mouse

**Comment by failiz** [comment]
> When you right click the resistor itself, does the menu also delay until the button is released again?

Yes, the menu only appears when releasing the button, both for the resistor or the label

**Comment by KjellMorgenstern** [comment]
I was able to reproduce it on windows as you described. Behavior of reacting on release vs on press is due to the OS conventions. The fix works on Windows (emulator), with Ubuntu, mouse and touchpad. 
I'll also try with a macbook, then add it to 1.0.3
